In [1]:
from mxnet import np, npx, autograd
npx.set_np()

In [2]:
x = np.arange(4.0)
x

array([0., 1., 2., 3.])

In [3]:
#By calling function below, allocating memory for differentiating millions of times
x.attach_grad()
#vector of results by calling partial derivative on every x 
x.grad

array([0., 0., 0., 0.])

In [4]:
# Place our code inside an `autograd.record` scope to build the computational
# graph
with autograd.record():
    y = 2*np.dot(x,x)
y

array(28.)

In [5]:
y.backward()
x.grad

array([ 0.,  4.,  8., 12.])

In [6]:
#gradient of multiplication of transpose of x and x is equal to 2x by gradient rule 4. and y is multiplied it by 2 then y must be equal to 4x
x.grad == 4*x

array([ True,  True,  True,  True])

In [7]:
# the sum is like y = x1 + x2 + x3 + x4 so its all partial derivatives are equal to 1
with autograd.record():
    y = x.sum()
y.backward()
# then gradient is equal to ones 
x.grad

array([1., 1., 1., 1.])

2.5.2. Backward for non-scalar value

In [8]:
# When we invoke `backward` on a vector-valued variable `y` (function of `x`),
# a new scalar variable is created by summing the elements in `y`. Then the
# gradient of that scalar variable with respect to `x` is computed
with autograd.record():
    y = x * x  # `y` is a vector
y.backward()
x.grad  # Equals to y = sum(x * x)

array([0., 2., 4., 6.])

2.5.3. Detaching computation

In [15]:
#end ehleed u iin gradient iig olsni daraa z ruu u-g orluulj bodoj baigaa. Tiimees z iin huvid u bol const utga baina.
with autograd.record():
    y = x*x
    u = y.detach()
    z = u*x
z.backward()
x.grad == u, x.grad, u

(array([ True,  True,  True,  True]),
 array([0., 1., 4., 9.]),
 array([0., 1., 4., 9.]))

In [16]:
y.backward()
x.grad == 2*x

array([ True,  True,  True,  True])

2.5.4. Computing the Gradient of Python Control Flow¶

In [36]:
def f(a):
    b = a * a
    return b

In [39]:
a = np.arange(4)
a.attach_grad()
with autograd.record():
    d = f(a)
d.backward()
a

array([0., 1., 2., 3.])

In [41]:
a.grad, d, a

(array([0., 2., 4., 6.]), array([0., 1., 4., 9.]), array([0., 1., 2., 3.]))