In [3]:
import torch
import numpy as np

In [2]:
torch.tensor([[1,23.2],[-3.3,4]])

tensor([[ 1.0000, 23.2000],
        [-3.3000,  4.0000]])

In [4]:
torch.tensor(np.array([[1,2],[3,4]]))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
torch.zeros([2,4], dtype = torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [7]:
cuda0 = torch.device("cuda:0")

In [9]:
torch.ones([2,4], dtype=torch.float64, device=cuda0)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [11]:
x = torch.tensor([[3,4,5],[4,3,4]])

In [12]:
print(x[1][2])

tensor(4)


In [13]:
x[0][0] = 8

In [14]:
x

tensor([[8, 4, 5],
        [4, 3, 4]])

In [15]:
x = torch.tensor([[1]])
x.item()

1

In [19]:
x = torch.tensor([[1, -1], [1,1]], requires_grad=True, dtype=torch.float32)
out = x.pow(2).sum()
out.backward()
x.grad, out

(tensor([[ 2., -2.],
         [ 2.,  2.]]),
 tensor(4., grad_fn=<SumBackward0>))