In [1]:
from mxnet import np, npx
npx.set_np()

In [2]:
A = np.arange(20).reshape(5, 4)
B = A.copy()  # Assign a copy of `A` to `B` by allocating new memory
A, A + B

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]),
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]]))

Matrix transpose operation

In [3]:
A.T, (A+B).T

(array([[ 0.,  4.,  8., 12., 16.],
        [ 1.,  5.,  9., 13., 17.],
        [ 2.,  6., 10., 14., 18.],
        [ 3.,  7., 11., 15., 19.]]),
 array([[ 0.,  8., 16., 24., 32.],
        [ 2., 10., 18., 26., 34.],
        [ 4., 12., 20., 28., 36.],
        [ 6., 14., 22., 30., 38.]]))

2.3.6.1. Non-Reduction Sum¶


In [4]:
#summing over an axis by not losing the dimensionality
sum_A = A.sum(axis=1, keepdims=True)
sum_A

array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]])

In [5]:
#above operation could be usefule like broadcasting operations like below one
A/sum_A

array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]])

In [6]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

2.3.7. Dot products

In [16]:
#dot product of two vector is equal to sum of elementwise multiplications
y = np.ones(4)
x = np.arange(4)
x,y, np.dot(x,y), np.sum(x*y)

(array([0., 1., 2., 3.]), array([1., 1., 1., 1.]), array(6.), array(6.))

2.3.8. Matrix vector products

In [12]:
A.shape, y.shape, np.dot(A,y)

((5, 4), (4,), array([ 6., 22., 38., 54., 70.]))

2.3.9. Matrix to matrix multiplication

In [18]:
B=np.ones(shape=(4,3))
np.dot(A,B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

2.3.10. Norms

In [21]:
#L2 norm 
u = np.array([4,-3])
np.linalg.norm(u)

array(5.)

In [22]:
#L1 norm 
np.abs(u).sum()

array(7.)

In [23]:
np.linalg.norm(np.ones((4,9)))

array(6.)