In [1]:
import numpy as np
import sys

In [15]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0, 8.0, 7.0], [1.0, 5.0, 4.]])
print(b)

[[9. 8. 7.]
 [1. 5. 4.]]


In [8]:
#Get dimension
a.ndim, b.ndim

(1, 2)

In [9]:
#Get shape
a.shape, b.shape

((3,), (2, 3))

In [14]:
#Get type
a.dtype, b.dtype

(dtype('int16'), dtype('float64'))

In [17]:
#Get size of 1 element on memory as bytes
a.itemsize, b.itemsize

(4, 8)

In [23]:
# Get total size, number of bytes
a.nbytes,b.nbytes

(12, 48)

In [27]:
a = np.array([[1,3,4,5,5,6,5],[3,4,2,4,3,5,2]] )
print(a)

[[1 3 4 5 5 6 5]
 [3 4 2 4 3 5 2]]


In [28]:
a.shape

(2, 7)

In [31]:
#Get a specific element 
a[1][-2] == a[1][5]

True

In [34]:
#Get a specific row
a[0, :] == a[0]

array([ True,  True,  True,  True,  True,  True,  True])

In [35]:
#Get a specific column
a[:, 2]

array([4, 2])

In [39]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]


array([3, 5, 6])

In [43]:
a[1,5] = 20
print(a)

a[:, 2] = [1,2]
print(a)

[[ 1  3  5  5  5  6  5]
 [ 3  4  5  4  3 20  2]]
[[ 1  3  1  5  5  6  5]
 [ 3  4  2  4  3 20  2]]


In [44]:
# 3-d example
b = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
#Get specific element (work outside in)
b[:,0,0]

array([1, 5])

In [49]:
#replace
b[:,1,:] = [[0,0], [8,8]]
b

array([[[1, 2],
        [0, 0]],

       [[5, 6],
        [8, 8]]])

In [54]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.ones((4,2,2), dtype="int16")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [58]:
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [60]:
#full like
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [69]:
# random decimal numbers
np.random.rand(4,3)


array([[0.24029863, 0.54542044, 0.07954722],
       [0.83096906, 0.58397739, 0.94366269],
       [0.58157315, 0.67124646, 0.66590772],
       [0.65542608, 0.77852013, 0.5324256 ]])

In [70]:
np.random.random_sample(a.shape)

array([[0.42450393, 0.74316501, 0.47741754, 0.9236885 , 0.47301133,
        0.75853444, 0.49316494],
       [0.67008562, 0.16163009, 0.97708112, 0.9320979 , 0.83170407,
        0.38490558, 0.02030469]])

In [74]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[2, 3, 2],
       [2, 6, 2],
       [3, 1, 0]])

In [76]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [86]:
b = a.copy()
b

array([[ 1,  3,  1,  5,  5,  6,  5],
       [ 3,  4,  2,  4,  3, 20,  2]])